# Generated by Django 5.2.17 on 2026-09-30 14:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgriInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Seeds', 'Seeds'), ('Fertilizers', 'Fertilizers'), ('Tools & Machinery', 'Tools & Machinery'), ('Other', 'Other')], db_index=True, max_length=24)),
                ('merchant', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('location', models.CharField(max_length=200)),
                ('rating', models.DecimalField(decimal_places=1, default=Decimal('4.7'), max_digits=2)),
                ('stock', models.CharField(max_length=60)),
                ('specs', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorporateBuyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=200, unique=True)),
                ('industry', models.CharField(max_length=120)),
                ('raw_material_needed', models.CharField(max_length=200)),
                ('monthly_volume_req', models.CharField(max_length=60)),
                ('offer_price', models.CharField(max_length=60)),
                ('unit_price_numeric', models.DecimalField(decimal_places=2, max_digits=14)),
                ('location', models.CharField(max_length=200)),
                ('quality_specs', models.JSONField(default=list)),
                ('escrow_deposit_locked', models.CharField(max_length=120)),
                ('contact_person', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('Maize', 'Maize'), ('Cassava', 'Cassava'), ('Soybeans', 'Soybeans'), ('Sesame', 'Sesame'), ('Other', 'Other')], db_index=True, max_length=16)),
                ('verified_buyer', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='ImportPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('origin', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=120)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('retail_price_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('target_units', models.PositiveSmallIntegerField()),
                ('reserved_units', models.PositiveSmallIntegerField(default=0)),
                ('description', models.TextField()),
                ('specs', models.JSONField(default=list)),
                ('group_savings', models.CharField(max_length=200)),
                ('estimated_days', models.PositiveSmallIntegerField(default=21)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EscrowContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('kind', models.CharField(choices=[('HARVEST', 'Harvest produce purchase'), ('OFFTAKE', 'Corporate offtake supply'), ('POOL', 'Group import pool'), ('INPUT', 'Agri-input purchase')], default='HARVEST', max_length=12)),
                ('buyer_label', models.CharField(blank=True, max_length=200)),
                ('seller_label', models.CharField(max_length=200)),
                ('item', models.CharField(max_length=250)),
                ('quantity', models.CharField(max_length=60)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('currency', models.CharField(choices=[('NGN', 'NGN'), ('cNGN', 'cNGN'), ('USDB', 'USDB')], max_length=8)),
                ('stage', models.PositiveSmallIntegerField(choices=[(1, 'Contract Drafted'), (2, 'Funds Locked'), (3, 'Quality Inspection'), (4, 'Settlement Released')], default=1)),
                ('quality_specs', models.CharField(blank=True, max_length=500)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escrows_as_buyer', to=settings.AUTH_USER_MODEL)),
                ('corporate_buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escrows', to='marketplace.corporatebuyer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, max_length=30, unique=True)),
                ('pool_units', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('quantity', models.CharField(blank=True, max_length=60)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('currency', models.CharField(choices=[('NGN', 'NGN'), ('cNGN', 'cNGN'), ('USDB', 'USDB')], max_length=8)),
                ('rail', models.CharField(choices=[('cngn', 'cNGN Stablecoin'), ('usdb', 'USDB (USD Stable)'), ('bank', 'NGN Fiat Bank Transfer')], default='cngn', max_length=8)),
                ('purpose', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=12)),
                ('virtual_account', models.CharField(blank=True, max_length=20)),
                ('bank_name', models.CharField(default='BMONI Settlement Bank (NIBSS)', max_length=120)),
                ('escrow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='marketplace.escrowcontract')),
                ('pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='marketplace.importpool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PoolParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('units', models.PositiveSmallIntegerField()),
                ('total_usd', models.DecimalField(decimal_places=2, max_digits=14)),
                ('escrow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.escrowcontract')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='marketplace.importpool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProduceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.CharField(max_length=200)),
                ('volume_available', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(default='MT', max_length=8)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('location', models.CharField(max_length=200)),
                ('specs', models.JSONField(default=list)),
                ('rating', models.DecimalField(decimal_places=1, default=Decimal('4.8'), max_digits=2)),
                ('category', models.CharField(choices=[('Grain', 'Grain'), ('Tuber', 'Tuber'), ('Oilseed', 'Oilseed'), ('Legume', 'Legume'), ('Other', 'Other')], default='Other', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produce_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplyProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tonnage', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=16)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('IN_ESCROW', 'Escrow Locked'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=12)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='marketplace.corporatebuyer')),
                ('escrow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.escrowcontract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ngn_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('cngn_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('usd_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
